# Shell variables
# Generated by 'wal'
# Special
background='#1c1b1a'
foreground='#e3d2ca'
cursor='#e3d2ca'

# Colors
color0='#1c1b1a'
color1='#F69665'
color2='#4A7A8B'
color3='#927D84'
color4='#1F96AE'
color5='#66A5B0'
color6='#9DB1B2'
color7='#e3d2ca'
color8='#9e938d'
color9='#F69665'
color10='#4A7A8B'
color11='#927D84'
color12='#1F96AE'
color13='#66A5B0'
color14='#9DB1B2'
color15='#e3d2ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
